### ISSUE TITLE
node 12 support

### ISSUE THREAD

**Issue by idan-at** [sonicdoe/native-hello-world#1]
Hi, I've tried to compile this module for node12, and failed.

Looks like `Nan::New<v8::FunctionTemplate>(Method)->GetFunction` expects context.
After fixing this issue (passed `Nan::New<v8::FunctionTemplate>(Method)->GetFunction(Nan::GetCurrentContext())`), looks like `module->Set` causes this error: `error: no matching member function for call to 'Set'`.

Tried updating `nan`, didn't help.

Any thoughts?

Thanks in advanced!

**Comment by sonicdoe** [comment]
Thank you for opening an issue! I’ve rewritten this addon using [N-API](https://nodejs.org/api/n-api.html) in https://github.com/sonicdoe/native-hello-world/commit/4cfe9dc147419867e539a12f6633e868abf31b54 which should work fine with Node.js v12. Let me know if you are still having issues with native-hello-world v2.0.0.

**Comment by idan-at** [comment]
@sonicdoe thanks for the super fast response! appreciate it :)
